"use-strict";
const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const contacts=new Schema({
    ContactName:{
        type:String,
        default:"",
    },
    EmailAddress:{
        type:String,
        default:"",
    },
    FirstName:{
        type:String,
        default:"",
    },
    LastName:{
        type:String,
        default:"",
    },
    POCity:{
        type:String,
        default:"",
    },
    POZipCode:{
        type:String,
        default:"",
    },
    POCountry:{
        type:String,
        default:"",
    },
    POAttentionTo:{
        type:String,
        default:"",
    },
    POAddressLine1:{
        type:String,
        default:"",
    },
    POAddressLine2:{
        type:String,
        default:"",
    },
    POAddressLine3:{
        type:String,
        default:"",
    },
    POAddressLine4:{
        type:String,
        default:"",
    },
    PORegion:{
        type:String,
        default:"",
    },
    SAAttentionTo:{
        type:String,
        default:"",
    },
    SAAddressLine1:{
        type:String,
        default:"",
    }, 
    SAAddressLine2:{
        type:String,
        default:"",
    }, 
    SAAddressLine3:{
        type:String,
        default:"",
    },
    SAAddressLine4:{
        type:String,
        default:"",
    },
    SACity:{
        type:String,
        default:"",
    },
    SARegion:{
        type:String,
        default:"",
    },
    SAZipCode:{
        type:String,
        default:"",
    },
    SACountry:{
        type:String,
        default:"",
    },
    PhoneNumber:{
        type:String,
        default:"",
    },
    FaxNumber:{
        type:String,
        default:"",
    },
    MobileNumber:{
        type:String,
        default:"",
    },
    DDINumber:{
        type:String,
        default:"",
    },
    SkypeName:{
        type:String,
        default:"",
    },
    BankAccountName:{
        type:String,
        default:"",
    },
    BankAccountNumber:{
        type:String,
        default:"",
    },
    BankAccountParticulars:{
        type:String,
        default:"",
    },
    TaxNumberType:{
        type:String,
        default:"",
    },
    TaxNumber:{
        type:String,
        default:"",
    },
    AccountsReceivableTaxCodeName:{
        type:String,
        default:"",
    },
    AccountsPayableTaxCodeName:{
        type:String,
        default:"",
    },
    Website:{
        type:String,
        default:"",
    },
    LegalName:{
        type:String,
        default:"",
    },
    Discount:{
        type:String,
        default:"",
    },
    CompanyNumber:{
        type:String,
        default:"",
    },
    DueDateBillDay:{
        type:String,
        default:"",
    },
    DueDateBillTerm:{
        type:String,
        default:"",
    },
    DueDateSalesDay:{
        type:String,
        default:"",
    },
    DueDateSalesTerm:{
        type:String,
        default:"",
    },
    SalesAccount:{
        type:String,
        default:"",
    },
    PurchasesAccount:{
        type:String,
        default:"",
    },
    TrackingName1:{
        type:String,
        default:"",
    },
    SalesTrackingOption1:{
        type:String,
        default:"",
    },
    PurchasesTrackingOption1:{
        type:String,
        default:"",
    },   
    TrackingName2:{
        type:String,
        default:"",
    },
    SalesTrackingOption2:{
        type:String,
        default:"",
    },
    PurchasesTrackingOption2:{
        type:String,
        default:"",
    },
    BrandingTheme:{
        type:String,
        default:"",
    },
    DefaultTaxBills:{
        type:String,
        default:"",
    },
    DefaultTaxSales:{
        type:String,
        default:"",
    },
    Person1FirstName:{
        type:String,
        default:"",
    },
    Person1LastName:{
        type:String,
        default:"", 
    },
    Person1Email:{
        type:String,
        default:"", 
    },
    Person1IncludeInEmail:{
        type:String,
        default:"", 
    },
    Person2FirstName:{
        type:String,
        default:"",
    },
    Person2LastName:{
        type:String,
        default:"", 
    },
    Person2Email:{
        type:String,
        default:"", 
    },
    Person2IncludeInEmail:{
        type:String,
        default:"", 
    },
    Person3FirstName:{
        type:String,
        default:"",
    },
    Person3LastName:{
        type:String,
        default:"", 
    },
    Person3Email:{
        type:String,
        default:"", 
    },
    Person3IncludeInEmail:{
        type:String,
        default:"", 
    },
    Person4FirstName:{
        type:String,
        default:"",
    },
    Person4LastName:{
        type:String,
        default:"", 
    },
    Person4Email:{
        type:String,
        default:"", 
    },
    Person4IncludeInEmail:{
        type:String,
        default:"", 
    },
    Person5FirstName:{
        type:String,
        default:"",
    },
    Person5LastName:{
        type:String,
        default:"", 
    },
    Person5Email:{
        type:String,
        default:"", 
    },
    Person5IncludeInEmail:{
        type:String,
        default:"", 
    },

})
module.exports=mongoose.model("contacts",contacts)